# Setup
title: Hussam Zaghal 🎮
author: Hussam Zaghal
email: h@zaghal.ca
tagline: Ideas, essays, and projects by Hussam Zaghal
url: https://hussam.fyi/
paginate: 5
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Hussam Zaghal
  url: https://twitter.com/hussamfyi
  email: h@zaghal.ca

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Now
    url: /now

  - title: Writing
    url: https://hussam.substack.com/
